// <auto-generated />
namespace Ecommerce01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Indices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Indices));
        
        string IMigrationMetadata.Id
        {
            get { return "201801202134316_Indices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
